#pragma once

#include "CoreGlobalSDevice/public.h"

#include "SDeviceCore/errors.h"

SDEVICE_RUNTIME_DATA_FORWARD_DECLARATION(CoreGlobal);
SDEVICE_INIT_DATA_FORWARD_DECLARATION(CoreGlobal);

SDEVICE_RUNTIME_DATA_DECLARATION(CoreGlobal) { };
SDEVICE_INIT_DATA_DECLARATION(CoreGlobal) { };

SDEVICE_HANDLE_DECLARATION(CoreGlobal);
SDEVICE_INTERNAL_ALIASES_DECLARATION(CoreGlobal);
